#!/usr/bin/env bash
# Claude Code PreToolUse guard (see AGENTS.md). Reads the tool call as JSON on
# stdin; exit 2 blocks the call and shows stderr to the model. Offline, fast.
# Wired from .claude/settings.json for the Bash / Edit / Write tools.
# NOTE: no `set -e` — this file is a matcher built on `[[ test ]] && deny`, and a
# non-matching test returns 1, which under errexit would abort before later rules.
set -u

payload=$(cat)

# jq is not guaranteed here; node is. Emit tool/command/file_path as three
# \x1f-separated fields with newlines/tabs flattened to spaces (safe for `read`,
# and whitespace runs are irrelevant to the matches below).
IFS=$'\x1f' read -r tool cmd path < <(printf '%s' "$payload" | node -e '
  let s = ""; process.stdin.on("data", d => s += d).on("end", () => {
    let j = {}; try { j = JSON.parse(s); } catch (_) {}
    const i = j.tool_input || {};
    const flat = v => (v == null ? "" : String(v).replace(/[\r\n\t]+/g, " "));
    process.stdout.write([j.tool_name || "", flat(i.command), flat(i.file_path)].join("\x1f"));
  });
')

deny() { printf 'BLOCKED [%s]: %s\n' "$1" "$2" >&2; exit 2; }

if [ "$tool" = "Bash" ]; then
  c=$cmd
  # terraform apply (plan/validate/init/import are allowed).
  [[ $c =~ (^|[^[:alnum:]_])terraform[[:space:]]+apply($|[^[:alnum:]_-]) ]] && \
    deny "terraform apply" "terraform apply is owner-run — produce a plan file instead (terraform plan -out=tfplan)."
  # gcloud sensitive surfaces (IAM / org policy / IAP / Cloud Run destructive/mutating).
  if [[ $c =~ (^|[^[:alnum:]_])gcloud($|[^[:alnum:]_-]) ]]; then
    [[ $c =~ (^|[[:space:]])iam($|[[:space:]]) ]]         && deny "gcloud iam"          "gcloud iam changes are owner-run — request the grant, don't self-apply."
    [[ $c =~ org-policies ]]                              && deny "gcloud org-policies" "gcloud org-policies are owner-run — do not modify org policy."
    [[ $c =~ (^|[[:space:]])iap($|[[:space:]]) ]]         && deny "gcloud iap"          "gcloud iap changes are owner-run — do not touch IAP."
    [[ $c =~ run[[:space:]]+services[[:space:]]+delete ]] && deny "gcloud run delete"   "deleting a Cloud Run service is owner-run — leave it to the owner."
    [[ $c =~ run[[:space:]]+services[[:space:]]+update ]] && deny "gcloud run update"   "mutating a live Cloud Run service is owner-run — deploy via the sanctioned pipeline."
    [[ $c =~ (add|remove)-iam-policy-binding ]]           && deny "gcloud iam-binding"  "IAM policy bindings are owner-run — request the binding, don't self-apply."
  fi
  # git add of everything (stage explicit pathspecs instead).
  [[ $c =~ (^|[^[:alnum:]_])git[[:space:]]+add[[:space:]]+(-A($|[[:space:]])|--all($|[[:space:]])|\.($|[[:space:]])) ]] && \
    deny "git add -A/./--all" "blanket staging is banned — stage explicit paths: git add path/to/file."
  # git push --force / -f.
  [[ $c =~ (^|[^[:alnum:]_])git[[:space:]]+push([[:space:]].*)?[[:space:]](--force|-f)($|[[:space:]]) ]] && \
    deny "git push --force" "force-push is banned — reconcile with the remote (git pull --rebase) and push a normal update."
  # bypassing verification (any tool).
  [[ $c =~ (^|[[:space:]])--no-verify($|[[:space:]]) ]] && \
    deny "--no-verify" "--no-verify bypasses the hooks that enforce discipline — fix the failure the hook reports instead."
  # git commit -a (short-flag cluster containing 'a', or --all).
  [[ $c =~ (^|[^[:alnum:]_])git[[:space:]]+commit[[:space:]].*(-[a-z]*a[a-z]*|--all)($|[[:space:]]) ]] && \
    deny "git commit -a" "git commit -a auto-stages tracked changes — stage explicit paths, then commit."
  exit 0
fi

if [ "$tool" = "Edit" ] || [ "$tool" = "Write" ]; then
  p=$path
  [[ $p =~ (^|/)vendor/agape-ts/ ]] && \
    deny "edit vendor/agape-ts" "vendor/agape-ts/ is generated by scripts/vendor-agape-ts.sh — edit upstream agape-ts and re-vendor, don't hand-edit the vendored copy."
  [[ $p =~ (^|/)VERSION\.md$ ]] && \
    deny "edit VERSION.md" "VERSION.md is the release source of truth — it changes only via the release process, not ad-hoc edits."
  exit 0
fi

exit 0
